"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown, HelpCircle, Sparkles } from "lucide-react";

interface FAQItem {
  question: string;
  answer: string;
}

const FAQS: FAQItem[] = [
  {
    question: "What is YatraSetu and how does 'Yatra Bane Seva' work?",
    answer: "YatraSetu connects regular trip booking with verified local restoration acts (beach cleanups, tree plantations, heritage preservation drives). Travelers can book their stay and transport, RSVP to a community seva event happening nearby, check in securely on-site, and earn redeemable Green Karma points and digital certificates.",
  },
  {
    question: "How does the AI Decongestion Engine choose alternative destinations?",
    answer: "Our Decongestion Engine calculates a dynamic crowd-pressure score using booking density trends, Open-Meteo climate advisories, and OpenStreetMap spatial data. When high pressure (🔴) is detected at saturated destinations like Manali or North Goa, it surfaces 2–3 tranquil alternatives (like Kasol, Tirthan Valley, or Agonda) and awards 250 bonus Seva points for booking them.",
  },
  {
    question: "How is volunteer attendance verified without fraud?",
    answer: "We employ a three-tier verification protocol: (1) A time-seeded rotating QR code generated by the verified event lead that changes every 15 seconds, (2) A browser-verified GPS perimeter check within 200m of the site, and (3) A timestamped selfie check-in. This prevents remote proxy attendance.",
  },
  {
    question: "Where and how can I redeem my Green Karma points?",
    answer: "Points earned through verified restoration events or booking decongested destinations can be redeemed on your next journey for eco-homestay discounts, state bus/train travel vouchers, and authorized monument entry tickets.",
  },
  {
    question: "How can student volunteers (NSS/NCC) benefit from YatraSetu?",
    answer: "Students from NSS and NCC chapters receive digitally verifiable Certificates of Seva complete with hours logged, location coordinates, and event leader attestations, formatted for inclusion in academic credentials and resumes.",
  },
  {
    question: "Is YatraSetu free for travelers and community organizers?",
    answer: "Yes! YatraSetu is 100% free for travelers, volunteers, and community leads. We partner with local homestays, NGOs, and tourism bodies under the Smart India Hackathon 2026 initiative.",
  },
];

export default function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const toggle = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="relative overflow-hidden bg-white py-24 sm:py-32">
      <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <div className="text-center">
          <span className="inline-flex items-center gap-2 rounded-full bg-amber-50 px-4 py-1.5 text-xs font-semibold text-amber-700 border border-amber-200">
            <HelpCircle className="h-3.5 w-3.5" />
            Frequently Asked Questions
          </span>
          <h2 className="mt-4 font-display text-3xl font-bold tracking-tight text-ink-900 sm:text-4xl">
            Everything You Need to Know
          </h2>
          <p className="mt-3 text-base text-ink-500 sm:text-lg">
            Answers to common questions about sustainable travel, seva verification, and points redemption.
          </p>
        </div>

        <div className="mt-12 space-y-4">
          {FAQS.map((faq, i) => {
            const isOpen = openIndex === i;
            return (
              <div
                key={i}
                className="overflow-hidden rounded-2xl border border-earth-200 bg-earth-50/50 transition-colors hover:border-earth-300"
              >
                <button
                  onClick={() => toggle(i)}
                  className="flex w-full items-center justify-between p-6 text-left"
                  aria-expanded={isOpen}
                >
                  <span className="font-display text-base sm:text-lg font-bold text-ink-900 pr-4">
                    {faq.question}
                  </span>
                  <div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-white border border-earth-200 transition-transform duration-200 ${isOpen ? "rotate-180 bg-amber-50 text-amber-600 border-amber-200" : "text-ink-500"}`}>
                    <ChevronDown className="h-4 w-4" />
                  </div>
                </button>
                <AnimatePresence>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.25 }}
                    >
                      <div className="px-6 pb-6 pt-1 text-sm sm:text-base leading-relaxed text-ink-600 border-t border-earth-200/60 mt-1">
                        {faq.answer}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
